### ISSUE TITLE
Consider application of `filename_patterns` to readers that accept directories

### ISSUE THREAD

**Issue by DragaDoncila** [napari/npe2#155]
### Description

Currently, readers with `accepts_directories: true` get passed all directories, regardless of whether or not they also declare any `filename_patterns`.

Based on [this discussion](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/directory.20name.20patterns.20in.20reader.20plugins.3F) in zulip, there is a user desire to have these `filename_patterns` be applied to directories as well. 

I remember in community discussions we semi-decided that if you want filename patterns to be applied, **and** preferences available, you should provide a custom extension to your directory. Currently, we don't apply `filename_patterns` at all, so this behavior is not supported (though we can separately support preference assignment in napari). 

The remaining questions are how these `filename_patterns` should be applied. It could be reasonably interpreted that they are applied to the directory name itself, or to the directory's contents. Indeed we may wish to support both use cases, so we need to make sure the interpretation is unambiguous.

### Proposed Spec Implementations

1. Add an explicit `directory_patterns` field to `reader_contributions`. Readers can provide both `directory_patterns` and `filename_patterns`. Directory names must match `directory_patterns` and directory contents must match `filename_patterns` for a path to be compatible with this reader. For example:

```yaml
# Only individual tiff files are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Single tiff reader
    filename_patterns:
    - '*.tiff' 
    accepts_directories: false 
```

or

```yaml
# All directories with one or more tiffs inside them are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Directory of tiff reader
    filename_patterns:
    - '*.tiff'
    accepts_directories: true
```

or

```yaml
# Directories matching directory_patterns with one or more tiffs inside them are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Super specific tiff reader
    filename_patterns:
    - '*.tiff'
    accepts_directories: true
    directory_patterns: ['*/my-special-folder']
```

2. Use the "glob style" `filename_patterns` to specifically match each case and document examples e.g. 

```yaml
# Only individual tiff files are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Single tiff reader
    filename_patterns:
    - '*.tiff' 
    accepts_directories: false 
```

or

```yaml
# All directories with one or more tiffs inside them are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Directory of tiff reader
    filename_patterns:
    - '*/*.tiff' # not too sure about this one
    accepts_directories: true
```

or

```yaml
# Directories named my-special-folder with one or more tiffs inside them are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Super specific tiff reader
    filename_patterns:
    - '*/my-special-folder/*.tiff'
    accepts_directories: true
```

### Other Considerations
- We should document recommended approaches for various common use cases e.g. (I don't know if this is what we recommend but we should come to a consensus):
    - if you have files scattered over a number of directories we recommend using a metadata file pointing to required associated information and building a reader for this metadata file
    - if you have a directory of associated files that should be read in a certain way you should consider adding a custom extension to your directory
    - others...?
- Are directories with extensions a special case? In my opinion they should be treated as not directories at all but rather a file-like path. We should definitely support filtering compatible directory readers with extensions
- Do we want to support any further incarnation of specifying the necessary files or directories that need to be present for a reader to be able to claim a file e.g. OME-zarr requires the presence of well-formatted `.zarray` and `.zgroup` files inside a directory named with a `.zarr` extension - should all of this be able to specified in the manifest? My personal opinion is no - this is the job of the `get_reader` function.

**Comment by vreuter** [comment]
Furthermore, it seems that, at least with `npe2` at version 0.7.5, the validation of plugin package manifest will fail if `filename_patterns` is removed (removing to make it clear it has no effect when `accept_directories` is set to `True`.

```console
🅇 Invalid! 1 validation error for PluginManifest
contributions -> readers -> 0 -> filename_patterns
  field required (type=value_error.missing)
```

**Comment by DragaDoncila** [comment]
Thanks for mentioning that @vreuter agreed that if we don't start respecting it for directories, it shouldn't be required. But I think ideally we choose one of the implementations above and start respecting it!

**Comment by psobolewskiPhD** [comment]
I like this example the best:
```
# Directories matching directory_patterns with one or more tiffs inside them are passed to this reader
  readers:
  - command: tiff_reader.read_tiffs
  - title: Super specific tiff reader
    filename_patterns:
    - '*.tiff'
    accepts_directories: true
    directory_patterns: ['*/my-special-folder']
```
It's the easiest to understand I think and the most flexible?

I totally see plugins wanting to write custom folders and read them.
I wonder if we could use this to address the issue in napari of round-tripping saving multiple layers.
https://github.com/napari/napari/issues/5460

**Comment by DragaDoncila** [comment]
> I wonder if we could use this to address the issue in napari of round-tripping saving multiple layers.

Ahh that old chestnut. I think we **could** but only if we always saved our folders with a specific string in the folder name or with a custom extension. So we could save `<user-entered-name>_napari/` and then add `directory_patterns: ['*/*_napari']` to our built-in manifest. Or we could save `<user-entered-name>.napari/` and then add the appropriate directory pattern. Of course if the user renamed the folder, we couldn't do anything about that. The only "foolproof" option there is to write a little flag file into the folder (and hope the user doesn't delete it, which they probably wouldn't).

**Comment by psobolewskiPhD** [comment]
I think putting napari in the dir name would be fine.
`.napari` sort of implies don't change this, so that would work, **but** I think it also implies that only napari can open it, while it's just a regular folder with regular stuff.
(I know people struggle with this a lot with .zarr vs .zarr/0 ...)

**Comment by DragaDoncila** [comment]
@willingc @Czaki and I discussed this at last Eurasia meeting, and we came up with a proposal we thought was pretty nice and might address these concerns:

- `filename_patterns` remains unchanged. They are only checked when an individual file **not** a directory is being opened. If a directory is being open, this field has no effect.
- we add an additional field called `directory_match_patterns` or similar. This field is a list of _match groups_. Each _match group_ is a list of glob-like patterns pertaining to the directory path **and** its contents. A directory path must match **all** globs in a single _match group_ in order for that group to be matched i.e. the glob over the directory path and its contents must not return an empty list. A directory path must match one or more _match groups_ for the reader to be considered compatible.

Here are some examples:

```yaml
  readers:
  - command: napari.read_napari_layers
  - title: Read folder of napari layers
    # maybe we make this optional?
    filename_patterns:
    - '*'
    accepts_directories: true
    directory_match_patterns: 
    # matches any folder whose name ends in napari **and** any folders containing a .napari file 
    - ['*/*napari/']
    - ['*/.napari']
```
```yaml
  readers:
  - command: napari-zarr.read_zarr
  - title: Read any zarr
    # maybe we make this optional?
    filename_patterns:
    - '*'
    accepts_directories: true
    directory_match_patterns: 
    # matches any folder whose name ends in .zarr **and** any folders containing a .zattrs file **and** any folders containing a zarr.json file
    - ['*/*.zarr/']
    - ['*/.zattrs']
    - ['*/zarr.json']
```

```yaml
  readers:
  - command: tiff-read.specific-tiff-reader
  - title: Read folders named fizz that contain tiffs
    # maybe we make this optional?
    filename_patterns:
    - '*'
    accepts_directories: true
    directory_match_patterns: 
    # matches a folder named fizz that contains one or more tiffs.
    - ['*/fizz/', '*/*.tiff]
```

This seems like a very powerful way to be able to specify both directory path patterns AND directory content? The reader would get given the directory path and it would be up to the plugin to determine which of the files inside it actually wants to read.

It occurs to me as I write this that maybe we need a way to distinguish whether a glob is supposed to match the directory path or directory contents? Or maybe it's just that if the pattern ends in a `/` it matches the directory path, and if it doesn't, it matches directory contents.

Curious what folks think. @psobolewskiPhD @brisvag (I saw you thumb up a comment so I'm sniping you for this 😆)
