### ISSUE TITLE
migration support for napari_experimental_provide_function hooks

### ISSUE THREAD

**Issue by nclack** [napari/npe2#47]
### Description

I discussed this in separate conversations w @tlambert03, @sofroniewn and in the plugin working group meeting.

One of the nice things about migrating these is that it makes it simple for people to integrate functions like these into napari without adding dependencies to their package (no npe2, magicgui, napari etc...just the manifest file)

The proposal is to migrate napari_experimental_provide_function hooks to be npe2 widget contributions. It sounds like something like this might work:

```yaml
name: myplugin
contributions:
  commands:
    - id: myplugin.func
      python_name: myplugin:my_typed_function
      title: Open dock widget for myplugin function
  widgets:
    - command: myplugin.func
      name: Functionality
      type: magicgui                #<-- new field 
```

Implementation should cover:
- [x] schema support
- [x] npe2 conversion tool support
- [ ] npe2 doc update
- [ ] npe2 cookiecutter update
