### ISSUE TITLE
bug: npe2 readers not prepared for lists of paths

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#81]
whether it should get handled on the napari side (before passing paths to `npe2`) or on the npe2 side, the npe2 reader in io_utils is not currently handling a list of strings properly.

with a contribution of:
```yaml
readers:
    ...
    filename_patterns: ['*.ext']
```

`iter_compatible_readers(['f1.ext', f2.ext'])` will  return `None`

a list of strings is what will be passed when "open as stack" is true.
